package IAmNotJustJess.destroyTheMonument.player.classes.upgrades;

public enum UpgradeAffection {
    MAX_HP,
    MOVEMENT_SPEED,
    MAIN_WEAPON_DAMAGE,
    MAIN_WEAPON_EFFECT,
    RANGED_WEAPON_DAMAGE,
    RANGED_ON_PROJECTILE_HIT_EFFECT,
    RANGED_WEAPON_EFFECT,
    ACTIVE_STRENGTH,
    ACTIVE_LONGEVITY,
    ACTIVE_EFFECT,
    PASSIVE_STRENGTH,
    PASSIVE_LONGEVITY,
    PASSIVE_EFFECT,
    ULTIMATE_STRENGTH,
    ULTIMATE_LONGEVITY,
    ULTIMATE_EFFECT
}
