plugin:
  version: 0 #DO NOT CHANGE THIS - IT MAY BREAK AUTOMATIC UPDATES

# NOTE: All the messages support Kyori's Adventure syntaxes! https://docs.advntr.dev/minimessage/index.html

settings:
  logZombieLoad: true
  logRangedLoad: true
  logWaveLoad: true
  logArenaLoad: true
  logGameStateChanges: true
  maxPlayersPerArena: 32
  startCountdownAtPlayers: 1
  countdownTime: 15
  countdownReductionPlayers: 32
  countdownReduceTo: 10
  delayBeforeNextWave: 5
  newWaveZombieKills: 45
  gameOverAfter: 240
  spawnZombiesDelay: 2
  waveCount: 80

  effects:
    explosiveDamage: 2
    explosiveAOE: 2.0
    slowingDuration: 3
    slowingAmplifier: 3
    slowingAOE: 1.25
    voidPower: 1.0
    voidAOE: 2.0
    magmaDamage: 1
    magmaDamagePerTicks: 4
    magmaDuration: 2
    magmaAOE: 2.0
    slimePower: 1.0
    slimeAOE: 2.0
    electricDuration: 0.5
    electricAOE: 2
    beehiveSpawnedAmount: 3

messages:
  plugin:
    name: "<gradient:#7edd7e:#95e595><bold>Zombie Apocalypse</bold></gradient>"
    command: "<#5ca4e0>"
    symbol: "<#555555>"
    headline: "<#aaaaaa>"

    zombies:
      level1:
        name: "<#7cffac>Wzmocniony"
        colorR: 124
        colorG: 255
        colorB: 172
      level2:
        name: "<#3f75ff>Niepowstrzymany"
        colorR: 63
        colorG: 117
        colorB: 255
      level3:
        name: "<#ffbc75>Ostateczny"
        colorR: 255
        colorG: 188
        colorB: 117

    guns:
      level0:
        primary: "<#dddddd>"
        secondary: "<#5e5e5e>"
      level1:
        primary: "<#7cffac>"
        secondary: "<#3e7f56>"
      level2:
        primary: "<#3f75ff>"
        secondary: "<#1f3a7f>"
      level3:
        primary: "<#ffbc75>"
        secondary: "<#7f5e3a>"

  formats:
    arenaPlayersFormat: "<#555555>[<#aaaaaa>%min%<#555555>/<#aaaaaa>%max%<#555555>]" # %min% - Players currently in the arena, %max% - Maximum players per arena
    bossbarFormat: "<#2d9c53>Fala <#38c268>%wave% <#555555>| <#2d9c53>Zabite zombie<#297041>: <#38c268>%zombie1%<#297041>/<#38c268>%zombie2% <#555555>| <#2d9c53>Przegrana za<#297041>: <#38c268>%time%" # %wave% - Wave, %zombie1% - Killed zombies in a wave, %zombie2% - Required zombie count until the next wave, %time% - Remaining time
    playerActionBar: "<#94255b>[<#bd447f>HP<#94255b>: <#bd447f>%hp1%<#94255b>/<#bd447f>%hp2%<#94255b>]      <#258194>[<#42a8bd>Poziom 0 <#258194>| <#42a8bd>0<#258194>/<#42a8bd>0<#258194>]" # %hp1% - Current HP, %hp2% - Max HP

  arena:
    playerJoinLobby: "<#5ca4e0>%player% <#aaaaaa>dołącza do areny." # %player% - Player
    playerLeaveLobby: "<#5ca4e0>%player% <#aaaaaa>opuszcza arenę." # %player% - Player
    minimumPlayersReached: "<newline><#aaaaaa>Na arenie jest <#5ca4e0>wystarczająca ilość graczy<#aaaaaa>!<newline><#aaaaaa>Odliczanie <#5ca4e0>rozpoczęte<#aaaaaa>!<newline>"
    reductionPlayersReached: "<newline><#aaaaaa>Arena jest <#5ca4e0>pełna<#aaaaaa>! <newline><#aaaaaa>Odliczanie <#5ca4e0>skrócone<#aaaaaa>!<newline>"
    arenaCountdown: "<#aaaaaa>Arena rozpocznie się za <#5ca4e0>%time%<#aaaaaa>." # %time% - Time until the arena starts
    arenaCountdownSubtitle: "<transition:#aaaaaa:#5ca4e0:%phase%>%time%" # %phase% - Transition phase, %time - Time until the arena starts
    weaponChange: "<#aaaaaa>Wybrano broń %weapon% o poziomie %level%<#aaaaaa>!<newline>Otrzymasz ją na następnej fali!" # %weapon% - selected weapon, %level% - level of the weapon
    arenaBeginExplenationTitles: "<#aaaaaa>Witaj na%break%<#aaaaaa>Twoje zadania:%break%<#aaaaaa>Twoje zadania:%break%<#aaaaaa>Twoje zadania:"  # %break% - Split for multiple titles
    arenaBeginExplenationSubtitles: "<#5ca4e0>Zombie Apocalypse<#aaaaaa>!%break%<#aaaaaa>Przetrwaj jak <#5ca4e0>najdłużej<#aaaaaa>!%break%<#aaaaaa>Zabijaj <#5ca4e0>zombie<#aaaaaa>!%break%" # %break% - Split for multiple subtitles
    arenaBeginExplenationMessages: "<newline><#aaaaaa>Witaj na <#5ca4e0>ZombieApocalypse<#aaaaaa>!<newline><newline><#aaaaaa>Obecnie grasz na zamkniętych testach <#5ca4e0>alpha<#aaaaaa>!<newline>%break% 
    <newline><#aaaaaa>Przetrwaj jak <#5ca4e0>najdłużej <#aaaaaa>walcząć z <#5ca4e0>licznymi falami Zombie<#aaaaaa>.<newline><newline><#aaaaaa>Im <#5ca4e0>większa fala<#aaaaaa>, tym <#5ca4e0>silniejsze stają się zombie<#aaaaaa>!<newline><#aaaaaa>Aktualnie arena <#5ca4e0>kończy się <#aaaaaa>po <#5ca4e0>80 fali<#aaaaaa>!<newline>%break%
    <newline><#aaaaaa>Zabijaj jak <#5ca4e0>najwięcej zombie<#aaaaaa>!<newline><newline><#aaaaaa>Po zabiciu <#5ca4e0>wymaganej ilości zombie<#aaaaaa> kolejna fala rozpocznie się <#5ca4e0>automatycznie<#aaaaaa>.<newline><newline><#aaaaaa>Zmieniaj bronie (jak narazie) pod komendą <#5ca4e0>/za tb <id> <poziom>,<newline><#5ca4e0> ID: 1 - 20, Poziom 0 - 3<newline>" # %break% - Split for multiple messages, <newline> - Split for multiple rows of messages
    arenaBeginTitle: "<#aaaaaa>Powodzenia!"
    arenaBeginSubtitle: "<#aaaaaa>Start za <#5ca4e0>5 sekund<#aaaaaa>!"
    arenaBeginMessages: "<newline><#aaaaaa>Powodzenia!<newline><newline><#aaaaaa>Pierwsza fala rozpoczenie się za <#5ca4e0>5 sekund<#aaaaaa>!<newline>" # <newline> - Split for multiple rows of messages
    nextWave: "<newline><#2d9c53>Fala <#38c268>%wave% <#aaaaaa>rozpoczęta.<newline>" # %wave% - Next wave
    nextWaveTitle: "<#2d9c53>Fala <#38c268>%wave%" # %wave% - Next wave
    nextWaveSubtitle10s: "<#555555>Zombie stają się <#2d9c53>potężniejsze<#555555>..."
    waveBeaten: "<#2d9c53>Fala <#38c268>%wave% <#aaaaaa>zakończona! Kolejna fala za <#2d9c53>5 sekund<#aaaaaa>..." # %wave% - Wave beaten
    waveBeatenBossbar: "<#2d9c53>Fala <#38c268>%wave%<#aaaaaa> zakończona."
    waveTimeout: "<#aaaaaa>Czas się <#e05c71>kończy<#aaaaaa>! Pozostało <#e05c71>%time% <#aaaaaa>do <#e05c71>przegranej!" # %time% - Time till losing
    playerDeathTitle: "<#e05c71>Umarłeś<#aaaaaa>!"
    playerDeathSubtitle: "<#aaaaaa>Odrodzenie nastąpi po starcie <#e05c71>kolejnej fali<#aaaaaa>!"
    playerDeathMessage: "<newline><#aaaaaa>Gracz <#e05c71>%player% <#aaaaaa>został <#e05c71>zabity<#aaaaaa>! Zostało <#e05c71>%alive% <#aaaaaa>żywych graczy!<newline>" # %player% - player, %alive% - alive players
    defeat: "<newline><#e05c71>Przegrana<#aaaaaa>... Zombie was <#e05c71>pokonały<#aaaaaa>...<newline>"
    defeatTitle: "<#e05c71>Przegrana.."
    defeatBossbar: "<#e05c71>Przegrana..."
    victory: "<newline><#5ce088>Zwycięstwo<#aaaaaa>! Zombie zostały <#5ce088>pokonane<#aaaaaa>!<newline>"
    victoryTitle: "<#5ce088>Zwycięstwo!"
    victoryBossbar: "<#5ce088>Zwycięstwo!"