plugin:
  version: 0 #DO NOT CHANGE THIS - IT MAY BREAK AUTOMATIC UPDATES

# NOTE: All the messages support Kyori's Adventure syntaxes! https://docs.advntr.dev/minimessage/index.html

settings:
  logZombieLoad: true
  logBossLoad: true
  logRangedLoad: true
  logWaveLoad: true
  logArenaLoad: true
  logGameStateChanges: true
  maxPlayersPerArena: 32
  startCountdownAtPlayers: 1
  countdownTime: 15
  countdownReductionPlayers: 32
  countdownReduceTo: 10
  delayBeforeNextWave: 5
  newWaveZombieKills: 45
  gameOverAfter: 240
  spawnZombiesDelay: 2
  waveCount: 80

  effects:
    explosiveDamage: 2
    explosiveAOE: 2.0
    slowingDuration: 3
    slowingAmplifier: 3
    slowingAOE: 1.25
    voidPower: 1.0
    voidAOE: 2.0
    magmaDamage: 1
    magmaDamagePerTicks: 4
    magmaDuration: 2
    magmaAOE: 2.0
    slimePower: 1.0
    slimeAOE: 2.0
    electricDuration: 0.5
    electricAOE: 2
    beehiveSpawnedAmount: 3

messages:
  plugin:
    name: "<gradient:#9dff66:#56ff49><bold>Zombie Apocalypse</bold></gradient>"
    command: "<#9dff66>"
    symbol: "<#555555>"
    headline: "<#dddddd>"

    zombies:
      level1:
        name: "<#98ff9a>Wzmocniony"
        colorR: 152
        colorG: 255
        colorB: 154
      level2:
        name: "<#87d5ff>Niepowstrzymany"
        colorR: 135
        colorG: 213
        colorB: 255
      level3:
        name: "<#d37bff>Ostateczny"
        colorR: 211
        colorG: 123
        colorB: 255

    guns:
      level0:
        primary: "<#dddddd>"
        secondary: "<#5e5e5e>"
      level1:
        primary: "<#98ff9a>"
        secondary: "<#4c7f4d>"
      level2:
        primary: "<#87d5ff>"
        secondary: "<#436a7f>"
      level3:
        primary: "<#d37bff>"
        secondary: "<#693d7f>"

  formats:
    arenaPlayersFormat: "<#555555>[<#dddddd>%min%<#555555>/<#dddddd>%max%<#555555>]" # %min% - Players currently in the arena, %max% - Maximum players per arena
    bossbarFormat: "<#DDDDDD>Fala <#FFD07A><bold>%wave%</bold> <#555555>| <#DDDDDD>Zabite zombie <#92FF7A>%zombie1%<#497D3D>/<#92FF7A>%zombie2% <#555555>| <#DDDDDD>Przegrana za: <#EA766E>%time%" # %wave% - Wave, %zombie1% - Killed zombies in a wave, %zombie2% - Required zombie count until the next wave, %time% - Remaining time
    bossbarBossFormat: "<#DDDDDD>Fala <#ffd07a><bold>%wave%</bold> <#555555>| <#DDDDDD>Pokonaj <#AD3624>bossa<#DDDDDD>! <#555555>| <#DDDDDD>Przegrana za: <#EA766E>%time%" # %wave% - Wave, %time% - Remaining time
    playerActionBar: "<#FF0741>❤ <#970D2D>| <#FF4B75>%hp1%/%hp2%          <#908405>| <#FFEC16>Poz. <#FFF58D>1 <#908405>|          <#4B8AFF>0/0 <#083C9A>| <#0C61FF>❇" # %hp1% - Current HP, %hp2% - Max HP

  arena:
    playerJoinLobby: "<#9dff66>%player% <#dddddd>dołącza do areny." # %player% - Player
    playerLeaveLobby: "<#9dff66>%player% <#dddddd>opuszcza arenę." # %player% - Player
    minimumPlayersReached: "<newline><#dddddd>Na arenie jest <#9dff66>wystarczająca ilość graczy<#dddddd>!<newline><#9dff66>Odliczanie <#9dff66>rozpoczęte<#dddddd>!<newline>"
    reductionPlayersReached: "<newline><#dddddd>Arena jest <#9dff66>pełna<#dddddd>! <newline><#dddddd>Odliczanie <#9dff66>skrócone<#dddddd>!<newline>"
    arenaCountdown: "<#dddddd>Arena rozpocznie się za <#9dff66>%time%<#dddddd>." # %time% - Time until the arena starts
    arenaCountdownSubtitle: "<transition:#dddddd:#9dff66:%phase%>%time%" # %phase% - Transition phase, %time - Time until the arena starts
    weaponChange: "<newline><#dddddd>Wybrano broń %weapon% o poziomie %level%<#dddddd>!<newline>Otrzymasz ją po starcie kolejnej fali!<newline>" # %weapon% - selected weapon, %level% - level of the weapon
    arenaBeginExplenationTitles: "<#dddddd>Witaj na%break%<#dddddd>Twoje zadania:%break%<#dddddd>Twoje zadania:%break%<#dddddd>Twoje zadania:"  # %break% - Split for multiple titles
    arenaBeginExplenationSubtitles: "<gradient:#9dff66:#56ff49><bold>Zombie Apocalypse</bold></gradient><#dddddd>!%break%<#dddddd>Przetrwaj jak <#9dff66>najdłużej<#dddddd>!%break%<#dddddd>Zabijaj <#9dff66>zombie<#dddddd>!%break%" # %break% - Split for multiple subtitles
    arenaBeginExplenationMessages: "<newline><#dddddd>Witaj na <#9dff66>ZombieApocalypse<#dddddd>!<newline><newline><#dddddd>Obecnie grasz na zamkniętych testach <#9dff66>alpha<#dddddd>!<newline>%break% 
    <newline><#dddddd>Przetrwaj jak <#9dff66>najdłużej <#dddddd>walcząć z <#9dff66>licznymi falami Zombie<#dddddd>.<newline><newline><#dddddd>Im <#9dff66>większa fala<#dddddd>, tym <#9dff66>silniejsze stają się zombie<#dddddd>!<newline><#dddddd>Aktualnie arena <#9dff66>kończy się <#dddddd>po <#9dff66>80 fali<#dddddd>!<newline>%break%
    <newline><#dddddd>Zabijaj jak <#9dff66>najwięcej zombie<#dddddd>!<newline><newline><#dddddd>Po zabiciu <#9dff66>wymaganej ilości zombie<#dddddd> kolejna fala rozpocznie się <#9dff66>automatycznie<#dddddd>.<newline><newline><#dddddd>Zmieniaj bronie (jak narazie) pod komendą <#9dff66>/za tb <id> <poziom>,<newline><#9dff66> ID: 1 - 20, Poziom 0 - 3<newline>" # %break% - Split for multiple messages, <newline> - Split for multiple rows of messages
    arenaBeginTitle: "<#dddddd>Powodzenia!"
    arenaBeginSubtitle: "<#dddddd>Start za <#9dff66>5 sekund<#dddddd>!"
    arenaBeginMessages: "<newline><#dddddd>Powodzenia!<newline><newline><#dddddd>Pierwsza fala rozpoczenie się za <#9dff66>5 sekund<#dddddd>!<newline>" # <newline> - Split for multiple rows of messages
    nextWave: "<newline><#dddddd>Fala <#ffd07a><bold>%wave%</bold> <#dddddd>się rozpoczyna...<newline>" # %wave% - Next wave
    nextWaveTitle: "<#dddddd>Fala <#ffd07a><bold>%wave%</bold>" # %wave% - Next wave
    nextWaveSubtitle10s: "<#555555>Zombie stają się <#AD3624>potężniejsze<#555555>..."
    waveBeaten: "<#dddddd>Fala <#ffd07a><bold>%wave%</bold> <#dddddd>zakończona! Kolejna fala za <#9dff66>5 sekund<#dddddd>..." # %wave% - Wave beaten
    waveBeatenBossbar: "<#dddddd>Fala <#ffd07a><bold>%wave%</bold><#dddddd> zakończona."
    waveTimeout: "<#dddddd>Czas się <#AD3624>kończy<#dddddd>! Pozostało <#AD3624>%time% <#dddddd>do <#AD3624>przegranej!" # %time% - Time till losing
    playerDeathTitle: "<#AD3624>Zabito cię...<#dddddd>"
    playerDeathSubtitle: "<#dddddd>Odrodzenie nastąpi po starcie <#e05c71>kolejnej fali<#dddddd>!"
    playerDeathMessage: "<newline><#dddddd>Gracz <#AD3624>%player% <#dddddd>został <#AD3624>zabity<#dddddd>! Zostało <#AD3624>%alive% <#dddddd>żywych graczy!<newline>" # %player% - player, %alive% - alive players
    bossAttack: "%boss% <#555555>użył umiejętności: <#9dff66>%attack%<#555555>!" # %boss% - boss name, %attack% - attack name
    defeat: "<newline><#AD3624>Przegrana<#dddddd>... Zombie was <#AD3624>pokonały<#dddddd>...<newline>"
    defeatTitle: "<#AD3624>Przegrana.."
    defeatBossbar: "<#AD3624>Przegrana..."
    victory: "<newline><#5ce088>Zwycięstwo<#dddddd>! Zombie zostały <#5ce088>pokonane<#dddddd>!<newline>"
    victoryTitle: "<#5ce088>Zwycięstwo!"
    victoryBossbar: "<#5ce088>Zwycięstwo!"