plugin:
  version: 0 #DO NOT CHANGE THIS - IT MAY BREAK AUTOMATIC UPDATES
  colour: §x§7§e§d§d§7§e

commands:
  colours:
    command: §x§5§c§a§4§e§0
    symbol: §x§5§5§5§5§5§5
    headline: §x§a§a§a§a§a§a