plugin:
  version: 0 #DO NOT CHANGE THIS - IT MAY BREAK AUTOMATIC UPDATES
  colour: §x§7§e§d§d§7§e

commands:
  colours:
    command: §x§5§c§a§4§e§0
    symbol: §x§5§5§5§5§5§5
    headline: §x§a§a§a§a§a§a

guns:
  colours:
    level0:
      primary: aaaaaa
      secondary: 555555
    level1:
      primary: 55ffff
      secondary: 2a7f7f
    level2:
      primary: ff55ff
      secondary: 7f2a7f
    level3:
      primary: ffaa00
      secondary: 7f5500