name: ZombieApocalypse
version: '${project.version}'
main: roulycraft.zombieapocalypse.ZombieApocalypse
api-version: 1.16
authors: [ justJess ]
description:
  A RoulyCraft minigame - Zombie Apocalypse
commands:
  za:
    description: Komenda bazowa do trybu Zombie Apocalypse
    usage: /<command> <argument> <argument>
