package roulycraft.zombieapocalypse.game;

public enum MessageType {
    PLAYER_JOIN, PLAYER_LEAVE, START_COUNTDOWN, REDUCE_COUNTDOWN, COUNTDOWN, CHANGE_WEAPON, START_EXPLENATION, START, WAVE_NEXT, WAVE_BEATEN, PLAYER_DEATH, VICTORY, DEFEAT, ONE_PLAYER, EVERYONE
}
