package IAmNotJustJess.destroyTheMonument.player.classes.effects;

public enum EffectType {
    DAMAGE_INCREASE_FLAT,
    DAMAGE_INCREASE_MULTIPLIER,
    DEAL_DAMAGE_FLAT,
    DEAL_DAMAGE_PERCENTAGE,
    DAMAGE_VULNERABILITY_FLAT,
    DAMAGE_VULNERABILITY_MULTIPLIER,
    DAMAGE_OVER_TIME_FLAT,
    DAMAGE_OVER_TIME_PERCENTAGE,
    POTION_EFFECT,
    HEAL_FLAT,
    HEAL_PERCENTAGE,
    HEAL_OVER_TIME_FLAT,
    HEAL_OVER_TIME_PERCENTAGE,
    PUSH_AWAY,
    PUSH_UP
}
